---
name: CI - Validate students.csv

on:
  pull_request:
    paths:
      - "data/**"
      - "ci_validate_students.py"
      - ".github/workflows/ci.yaml"

jobs:
  validate:
    name: CI - Validate students.csv
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run validation script
        run: python ci_validate_students.py
